export const translations = {
  "pt-BR": {
    labels: {
      ejaCourses: "Cursos EJA",
      ejaStudents: "Alunos EJA",
      ejaSubmitFormTitles: "Título Formulário EJA",
      profisSubmitFormTitles: "Título Formulário Profissionalizante",
      profisStudents: "Alunos Profissionalizante",
      ProfisCourses: "Cursos Profissionalizantes",
      localhost: "Administração",
      Subjects: "Matérias",
      Cards: "Cards Página Principal",
      Faq: "Perguntas e Repostas",
      Footer: "Rodapé",
      Home: "Página Principal",
      Students: "Estudantes",
      show: {
        true: "Sim",
        false: "Não",
        null: "Não",
      },
    },
    buttons: {
      contactUs: "Entrar em contato",
    },
    properties: {
      subject: "Matéria",
      name: "Nome",
      uploadImage: "Imagem do upload img",
      updatedAt: "Data de Atualização",
      createdAt: "Data de Criação",
      start_date: "Data de Início",
      end_date: "Data de Fim",
      id: "Id",
      title: "Título",
      text: "Texto",
      show: "Mostrar",
      question: "Pergunta",
      answer: "Resposta",
      email: "Email",
      cell_phone: "Número de celular",
      landline: "Telefone fixo",
      emergency_phone: "Telefone de emergência",
      whatsappLink: "Link do Whatsapp",
      facebookLink: "Link do Facebook",
      instagramLink: "Link do Instagram",
      youtubeLink: "Link do Youtube",
      siteLink: "Link do Site",
      image: "Imagem apenas img",
      status: "Status",
      medical_report: "Laudo Médico",
      description: "Descrição",
      morningShiftAvailable: "Turno Matutino Disponível",
      afternoonShiftAvailable: "Turno Vespertino Disponível",
      nightShiftAvailable: "Turno Noturno Disponível"
    
    },
    actions: {
      viewIndividualPdf: "Visualizar PDF do aluno",
    },
    components: {
      Login: {
        welcomeHeader: "Seja Bem-vindo",
        welcomeMessage: "ao painel admnistrativo CESAS!",
      },
    },
  },
};
