export const translations = {
  "pt-BR": {
    labels: {
      ejaCourses: "Cursos EJA",
      ejaStudents: "Alunos EJA",
      ejaSubmitFormTitles: "Título Formulário EJA",
      profisSubmitFormTitles: "Título Formulário Profissionalizante",
      profisStudents: "Alunos Profissionalizante",
      ProfisCourses: "Cursos Profissionalizantes",
      Coordinators: "Coordenadores",
      Staffs: "Diretores e Secretário",
      Supervisions: "Equipe Supervisão",
      TeachingStaffs:"Equipe Docente",
      localhost: "Administração",
      Subjects: "Matérias",
      Cards: "Cards Página Principal",
      EjaFaqs: "Perguntas e Repostas EJA",
      ProfisFaqs: "Perguntas e Repostas Profissionalizante",
      Footer: "Rodapé",
      Homes: "Mural Página Principal",
      Events: "Eventos",
      Students: "Estudantes",
      show: {
        true: "Sim",
        false: "Não",
        null: "Não",
      },
      morningShiftAvailable: {
        true: "Sim",
        false: "Não",
        null: "Não",
      },
      afternoonShiftAvailable: {
        true: "Sim",
        false: "Não",
        null: "Não",
      },
      nightShiftAvailable: {
        true: "Sim",
        false: "Não",
        null: "Não",
      },
      disabledStudent: {
        true: "Sim",
        false: "Não",
        null: "Não",
      },
      recordlessStudent: {
        true: "Sim",
        false: "Não",
        null: "Não",
      },
      legacyStudent: {
        true: "Sim",
        false: "Não",
        null: "Não",
      },
    },
    buttons: {
      contactUs: "Entrar em contato",
    },
    properties: {
      director: "Diretor",
      vicedirector: "Vice-Diretor",
      secretary: "Secretário",
      subject: "Matéria",
      name: "Nome",
      uploadImage: "Imagem do upload img",
      updatedAt: "Data de Atualização",
      createdAt: "Data de Criação",
      start_date: "Data de Início",
      end_date: "Data de Fim",
      id: "Id",
      title: "Título",
      text: "Texto",
      show: "Mostrar",
      question: "Pergunta",
      answer: "Resposta",
      email: "Email",
      cell_phone: "Número de celular",
      cellphoneNumber: "Número de celular",
      landline: "Telefone fixo",
      landlinePhone: "Telefone fixo",
      emergency_phone: "Telefone de emergência",
      emergencyPhone: "Telefone de emergência",
      phone: "Telefone",
      whatsappLink: "Link do Whatsapp",
      facebookLink: "Link do Facebook",
      instagramLink: "Link do Instagram",
      youtubeLink: "Link do Youtube",
      siteLink: "Link do Site",
      image: "Imagem apenas img",
      status: "Status",
      state: "Estado",
      medical_report: "Laudo Médico",
      description: "Descrição",
      morningShiftAvailable: "Turno Matutino Disponível",
      afternoonShiftAvailable: "Turno Vespertino Disponível",
      nightShiftAvailable: "Turno Noturno Disponível",
      studentMedicalReport: "Laudo Médico",
      gender: "Gênero",
      fathersName: "Nome do Pai",
      mothersName: "Nome da Mãe",
      address: "Endereço",
      cep: "CEP",
      naturality: "Naturalidade",
      nationality: "Nacionalidade",
      cpf: "CPF",
      birthDate: "Data de Nascimento",
      specialNecessity: "Necessidades Especiais",
      levelOfEducation: "Nível de Educação",
      disabledStudent: "Debilitado?",
      applyShift: "Turno Pretendido",
      applyCourse: "Curso Pretendido",
      studentMedicalReport: "Laudo Médico",
      studentAcademicRecord: "Histórico Escolar",
      responsibleId: "Identidade do Responsável",
      responsibleName: "Nome do Responsável",
      studentProofOfResidence: "Comprovante de Residência",
      ethnicity: "Cor/Raça",
      studentId: "Identidade",
      idIssuingBody: "Orgão Expeditor da Identidade",
      idExpDate: "Data de Expedição da Identidade",
      idNumber: "Número da Identidade",
      socialName: "Nome Social",
      recordlessStudent: "Tem Registro Escolar?",
      legacyStudent: "Já foi Estudante?",
      shift: "Turno",
      studentPhoto: "Foto do Estudante",
      applyType: "Tipo de Matrícula",
    },
    actions: {
      downloadSinglePdf: "Baixar PDF(s) (Individual)",
      downloadAllPdfs: "Baixar PDF(s) (Todos)",
      downloadSelectedPdfs: "Baixar PDF(s) (Selecionados)",

      downloadSingleCsv: "Baixar Csv(s) (Individual)",
      downloadAllCsvs: "Baixar Csv(s) (Todos)",
      downloadSelectedCsvs: "Baixar Csv(s) (Selecionados)",
    },
    components: {
      Login: {
        welcomeHeader: "Seja Bem-vindo",
        welcomeMessage: "ao painel admnistrativo CESAS!",
      },
    },
  },
};
