export const translations = {
  "pt-BR": {
    labels: {
      Courses: "Cursos",
      localhost: "Administração",
      Subjects: "Matérias",
      Cards: "Cards Página Principal",
      Faq: "Perguntas e Repostas",
      Footer: "Rodapé",
      Home: "Página Principal",
      Students: "Estudantes",
      show: {
        true: "Sim",
        false: "Não",
        null: "Não",
      },
    },
    buttons: {
      contactUs: "Entrar em contato",
    },
    properties: {
      subject: "Matéria",
      name: "Nome",
      uploadImage: "Imagem",
      updatedAt: "Data de Atualização",
      createdAt: "Data de Criação",
      start_date: "Data de Início",
      end_date: "Data de Fim",
      id: "Id",
      title: "Título",
      text: "Texto",
      show: "Mostrar",
      question: "Pergunta",
      answer: "Resposta",
      email: "Email",
      cell_phone: "Número de celular",
      landline: "Telefone fixo",
      emergency_phone: "Telefone de emergência",
      whatsappLink: "Link do Whatsapp",
      facebookLink: "Link do Facebook",
      instagramLink: "Link do Instagram",
      youtubeLink: "Link do Youtube",
      siteLink: "Link do Site",
      image: "Imagem ",
      status: "Status",
      medical_report: "Laudo Médico",
    },
  },
};
